<?php
/** @var $block Impression */
/** @var $escaper \Magento\Framework\Escaper */

use Mygento\Metrika\Block\Tracker\Impression;

$items = $block->getImpressionItems();

$currencyCode = $escaper->escapeJs($block->getCurrentCurrencyCode());
$categoryName = $escaper->escapeJs($block->getCategoryName());
$productSelector = $escaper->escapeJs($block->getProductSelector());
$containerName = $escaper->escapeJs($block->getConfig('container_name'));
$productIdAttr = $escaper->escapeJs($block->getConfig('skuAttr'));
?>
<?php if (!empty($items)): ?>
<script>
    (function(containerName, payload) {
        window[containerName] = window[containerName] || [];
        window[containerName].push(payload);
    })('<?php echo $containerName; ?>', {
        ecommerce: {
            currencyCode: '<?php echo $currencyCode; ?>',
            impressions: <?= $block->jsonEncode($items); ?>
        }
    });
</script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "body": {
            "Mygento_Metrika/js/click-tracking": {
                "categoryName": "<?php echo $categoryName; ?>",
                "containerName": "<?php echo $containerName; ?>",
                "currencyCode": "<?php echo $currencyCode; ?>",
                "productSelector": "<?php echo $productSelector; ?>",
                "productIdAttr": "<?php echo $productIdAttr; ?>"
            }
        }
    }
</script>
