<?php
/** @var $block Impression */

use Mygento\Metrika\Block\Tracker\Impression;

$items = $block->getImpressionItems();

$currencyCode = $block->getCurrentCurrencyCode();
$categoryName = $block->getCategoryName();
$productSelector = $block->getProductSelector();
$containerName = $block->getConfig('container_name');
?>
<?php if (!empty($items)): ?>
<script>
    (function(containerName, payload) {
        window[containerName] = window[containerName] || [];
        window[containerName].push(payload);
    })('<?php echo $containerName; ?>', {
        ecommerce: {
            currencyCode: '<?php echo $block->escapeJs($currencyCode); ?>',
            impressions: <?= json_encode($items); ?>
        }
    });
</script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "body": {
            "Mygento_Metrika/js/click-tracking": {
                "categoryName": "<?php echo $block->escapeJs($categoryName); ?>",
                "containerName": "<?php echo $containerName; ?>",
                "currencyCode": "<?php echo $block->escapeJs($currencyCode); ?>",
                "productSelector": "<?php echo $block->escapeJs($productSelector); ?>"
            }
        }
    }
</script>
