<?php
/** @var $block Tracker */
/** @var $escaper Escaper */

use Magento\Framework\Escaper;
use Mygento\Metrika\Block\Tracker;

$code = $block->getCode();
$options = $block->getOptions();
$currencyCode = $escaper->escapeJs($block->getCurrentCurrencyCode());
$containerName = $escaper->escapeJs($block->getConfig('container_name'));
$productIdAttr = $escaper->escapeJs($block->getConfig('skuAttr'));
?>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    window.<?php echo $containerName;?> = window.<?php echo $containerName;?> || [];

    (function(m,e,t,r,i,k,a){
        m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();
        k=e.createElement(t),a=e.getElementsByTagName(t)[0];
        k.async=1;k.src=r;a.parentNode.insertBefore(k,a);
    })(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

    ym(<?php echo $code;?>, "init", <?php echo $block->jsonEncode($options);?>);
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/<?php echo $code;?>" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<script type="text/x-magento-init">
    {
        "body": {
            "Mygento_Metrika/js/cart-tracking": {
                "containerName": "<?php echo $containerName;?>",
                "currencyCode": "<?php echo $currencyCode; ?>",
                "productIdAttr": "<?php echo $productIdAttr; ?>"
            }
        }
    }
</script>

<?php
echo $block->getChildHtml();
