<?php
/**
 * @var $block Category
 */

use Mygento\Metrika\Block\Tracker\Category;

$category = $block->getCurrentCategory();
?>

<script>
require([
    'jquery',
    'Mygento_Metrika/js/category-tracking'
], function($) {
    'use strict';

    $('.products-grid, .products-list').categoryTracking({
        categoryName: '<?php echo $category->getName(); ?>',
        containerName: '<?php echo $block->getConfig('container_name'); ?>',
        currencyCode: '<?php echo $block->getCurrentCurrencyCode(); ?>',
        productSelector: '<?php echo $block->getConfig('product_selector'); ?>'
    });
});
</script>
